{% set name = "jupyterlab-favorites" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ae1d7e816f9f041d8eab13e76f7316bcef15d0bcee4e3031248325361f436672

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0

test:
  requires:
    - jupyterlab >=4.0.0,<5.0.0
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/favorites.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-favorites
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Add the ability to save favorite folders to JupyterLab for quicker browsing.

extra:
  recipe-maintainers:
    - fcollonval
